POST http://localhost:4000/login
Content-Type: application/json

    {
    "username": "test",
    "password": "test"
    }


###
GET http://localhost:3001/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1NTg2OTQ4MywiZXhwIjoxNjU1ODczMDgzfQ.iITgy7XcadtC9s9NzqoCnFn8WqmyogtreRm-opBNpO8
###
GET http://localhost:3001/api/products/computer/accessories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1NTg5NjU0NSwiZXhwIjoxNjU1OTAwMTQ1fQ.kJVYJJaKEC7Pqa-GENL3bOeDiZKzBE9TDltZRz54haM
###
GET http://localhost:3001/api/products/tech/va
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1NTg5NjU0NSwiZXhwIjoxNjU1OTAwMTQ1fQ.kJVYJJaKEC7Pqa-GENL3bOeDiZKzBE9TDltZRz54haM
###
POST http://localhost:3001/api/products/search/alaoui
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTY1NTkwMDI5NiwiZXhwIjoxNjU1OTAzODk2fQ.FLiDeb-HpDx2aC_R9Mhkk7aXVOHL5BcKCI-g7vpeAuQ


